#!/usr/bin/with-contenv bash
#shellcheck shell=bash

readarray -td' ' local_ip <<< "$(hostname -I)"
UPD_IN_PORT="${UPD_IN_PORT:-9000}"

if [[ -z "${SBS_TARGET_HOST}" ]]; then
    echo "[ais2adsb] FATAL: SBS_TARGET_HOST not defined"
    sleep infinity
fi
if [[ -z "${SBS_TARGET_PORT}" ]]; then
    echo "[ais2adsb] FATAL: SBS_TARGET_IP not defined"
    sleep infinity
fi

echo "[ais2adsb] Starting ais2adsb version $(cat /.CONTAINER_VERSION 2>/dev/null) with this command line:"
echo "[ais2adsb] /usr/local/bin/ais2adsb.py ${local_ip[0]} ${UPD_IN_PORT} ${SBS_TARGET_HOST} ${SBS_TARGET_PORT} $INCLUDE_SHIPS"

# shellcheck disable=SC2086
/usr/local/bin/ais2adsb.py "${local_ip[0]}" "${UPD_IN_PORT}" "${SBS_TARGET_HOST}" "${SBS_TARGET_PORT}" $INCLUDE_SHIPS 2>&1 | mawk -W Interactive '{print "[ais2adsb] " $0}'
